#!/usr/bin/env bash
# Downloads the assets of an exporter release and repackages them keeping only the files that Agent Control
# needs (the integration and the exporter binaries, placed at the root of the archive).
#
# Usage: agent_control_repackage.sh <tag> <artifacts_json> <output_dir>
#   artifacts_json: JSON array as generated by agent_control_resolve.sh
#   output_dir:     where the packages and binaries.json (the list of packages to upload) are written
#
# Requires GH_TOKEN and GITHUB_REPOSITORY (or REPO) to be set, and gh, jq and tar to be installed.
set -euo pipefail

tag=${1:?usage: $0 <tag> <artifacts_json> <output_dir>}
artifacts=${2:?usage: $0 <tag> <artifacts_json> <output_dir>}
output_dir=${3:?usage: $0 <tag> <artifacts_json> <output_dir>}
repo=${REPO:-${GITHUB_REPOSITORY:?GITHUB_REPOSITORY or REPO must be set}}

work_dir=$(mktemp -d)
trap 'rm -rf "${work_dir}"' EXIT
mkdir -p "${output_dir}"
output_dir=$(cd "${output_dir}" && pwd)
binaries='[]'

while IFS= read -r artifact; do
  name=$(jq -r '.name' <<< "${artifact}")
  os=$(jq -r '.os' <<< "${artifact}")
  arch=$(jq -r '.arch' <<< "${artifact}")
  format=$(jq -r '.format' <<< "${artifact}")
  source_asset=$(jq -r '.source_asset' <<< "${artifact}")
  source_format=$(jq -r '.source_format' <<< "${artifact}")

  if [ "${source_format}" != "tar.gz" ] || [ "${format}" != "tar+gzip" ]; then
    echo "::error::Unsupported formats for '${name}': ${source_format} -> ${format}"
    exit 1
  fi

  echo "=== Processing '${name}' (${source_asset})"
  mkdir -p "${work_dir}/${name}/download" "${work_dir}/${name}/extracted" "${work_dir}/${name}/keep"
  gh release download "${tag}" --repo "${repo}" --pattern "${source_asset}" --dir "${work_dir}/${name}/download" --clobber
  tar xf "${work_dir}/${name}/download/${source_asset}" -C "${work_dir}/${name}/extracted"

  while IFS= read -r keep_file; do
    if [ ! -f "${work_dir}/${name}/extracted/${keep_file}" ]; then
      echo "::error::'${keep_file}' not found in ${source_asset}"
      exit 1
    fi
    cp "${work_dir}/${name}/extracted/${keep_file}" "${work_dir}/${name}/keep/"
  done < <(jq -r '.keep_files[]' <<< "${artifact}")

  package="${output_dir}/${name}.tar.gz"
  tar czf "${package}" -C "${work_dir}/${name}/keep" .
  echo "  -> ${package}"

  binaries=$(jq -c --arg name "${name}" --arg path "${package}" --arg os "${os}" --arg arch "${arch}" --arg format "${format}" \
    '. + [{name: $name, path: $path, os: $os, arch: $arch, format: $format}]' <<< "${binaries}")
done < <(jq -c '.[]' <<< "${artifacts}")

echo "${binaries}" > "${output_dir}/binaries.json"
echo "Repackaged: ${binaries}"
